/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tarde
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class IncidenciaGestor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IncidenciaGestor.class.getName());

    /**
     * Creates new form IncidenciaGestor
     */
    public IncidenciaGestor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIdIncidencia = new javax.swing.JLabel();
        jTextFieldIdIncidencia = new javax.swing.JTextField();
        jTextFieldTecnico = new javax.swing.JTextField();
        jLabelTecnico = new javax.swing.JLabel();
        Asignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIdIncidencia.setText("Id Incidencia");

        jLabelTecnico.setText("Nombre del Técnico");

        Asignar.setText("Asignar");
        Asignar.addActionListener(this::AsignarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdIncidencia)
                    .addComponent(jLabelIdIncidencia))
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTecnico)
                    .addComponent(jLabelTecnico))
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(Asignar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIdIncidencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIdIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(Asignar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarActionPerformed
        // TODO add your handling code here:
        String idIncidenciaStr = jTextFieldIdIncidencia.getText().trim();
        String nombreTecnico = jTextFieldTecnico.getText().trim();

        if (idIncidenciaStr.isEmpty() || nombreTecnico.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena ambos campos.");
            return;
        }

        try (Connection conn = ConexionDB.conectar()) {
            String sqlCheck = "SELECT estado FROM INCIDENCIA WHERE id = ?";
            PreparedStatement psCheck = conn.prepareStatement(sqlCheck);
            psCheck.setInt(1, Integer.parseInt(idIncidenciaStr));
            ResultSet rs = psCheck.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "La incidencia con ID " + idIncidenciaStr + " no existe.");
                return;
            }

            if (!"En espera".equals(rs.getString("estado"))) {
                JOptionPane.showMessageDialog(this, "Solo se pueden asignar incidencias que estén 'En espera'.");
                return;
            }

            String sqlTecnico = "SELECT id FROM USUARIO WHERE nombre = ? AND id_perfil = 2";
            PreparedStatement psTec = conn.prepareStatement(sqlTecnico);
            psTec.setString(1, nombreTecnico);
            ResultSet rsTec = psTec.executeQuery();

            if (!rsTec.next()) {
                JOptionPane.showMessageDialog(this, "No se encontró ningún técnico con el nombre: " + nombreTecnico);
                return;
            }
            int idTecnico = rsTec.getInt("id");

            String sqlContar = "SELECT COUNT(*) AS total FROM INCIDENCIA WHERE id_tecnico_asignado = ? AND estado = 'Asignada'";
            PreparedStatement psContar = conn.prepareStatement(sqlContar);
            psContar.setInt(1, idTecnico);
            ResultSet rsContar = psContar.executeQuery();

            if (rsContar.next()) {
                int totalAsignadas = rsContar.getInt("total");
                if (totalAsignadas >= 5) {
                    JOptionPane.showMessageDialog(this, "El técnico " + nombreTecnico + " ya tiene " + totalAsignadas + " incidencias asignadas. (Límite: 5)");
                    return;
                }
            }

            String sqlUpdate = "UPDATE INCIDENCIA SET id_tecnico_asignado = ?, estado = 'Asignada' WHERE id = ?";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setInt(1, idTecnico);
            psUpdate.setInt(2, Integer.parseInt(idIncidenciaStr));

            int filas = psUpdate.executeUpdate();
            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Incidencia asignada correctamente a " + nombreTecnico);
                this.dispose();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la incidencia debe ser un número.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_AsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IncidenciaGestor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asignar;
    private javax.swing.JLabel jLabelIdIncidencia;
    private javax.swing.JLabel jLabelTecnico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIdIncidencia;
    private javax.swing.JTextField jTextFieldTecnico;
    // End of variables declaration//GEN-END:variables
}
