
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class IncidenciaUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IncidenciaUsuario.class.getName());

    /**
     * Creates new form Incidencia
     */
    private int idUsuario;

    public IncidenciaUsuario() {
        initComponents();

    }

    public IncidenciaUsuario(int id) {
        initComponents();
        setLocationRelativeTo(null);
        this.idUsuario = id;
        cargarCombosDesdeBD();
    }
    private void cargarCombosDesdeBD() {

    cargarCombo(jComboBoxTipo,
        "SELECT descripcion FROM TIPO_INCIDENCIA ORDER BY descripcion");

    cargarCombo(jComboBoxEspacio,
        "SELECT nombre FROM ESPACIO ORDER BY nombre");

    cargarCombo(jComboBoxDispositivo,
        "SELECT nombre FROM DISPOSITIVO ORDER BY nombre");
}
    private void cargarCombo(javax.swing.JComboBox<String> combo, String sql) {

    combo.removeAllItems();

    try (Connection conn = ConexionDB.conectar();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            combo.addItem(rs.getString(1)); 
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error cargando combo: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEspacio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDispositivo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxPrioridad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jButtonCrear = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("NUEVA INCIDENCIA");

        jLabel3.setText("Tipo de incidencia: ");

        jComboBoxTipo.addActionListener(this::jComboBoxTipoActionPerformed);

        jLabel4.setText("Espacio de incidencia: ");

        jLabel5.setText("Dispositivo:");

        jLabel6.setText("Prioridad: ");

        jComboBoxPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));

        jLabel7.setText("Descripción: ");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(this::jButtonCrearActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonCrear)
                        .addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxDispositivo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxEspacio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCrear))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed
    private int obtenerIdTipoIncidencia(String descripcion) throws Exception {
        Connection conn = ConexionDB.conectar();

        String sql = "SELECT id FROM TIPO_INCIDENCIA WHERE descripcion = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, descripcion);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int id = rs.getInt("id");
            rs.close();
            ps.close();
            conn.close();
            return id;
        }

        rs.close();
        ps.close();
        conn.close();
        throw new Exception("Tipo de incidencia no encontrado");
    }

    private int obtenerIdEspacio(String nombre) throws Exception {
        Connection conn = ConexionDB.conectar();

        String sql = "SELECT id FROM ESPACIO WHERE nombre = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nombre);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int id = rs.getInt("id");
            rs.close();
            ps.close();
            conn.close();
            return id;
        }

        rs.close();
        ps.close();
        conn.close();
        throw new Exception("Espacio no encontrado");
    }

    private Integer obtenerIdDispositivo(String nombre) throws Exception {
        if (nombre == null || nombre.isEmpty()) {
            return null;
        }

        Connection conn = ConexionDB.conectar();

        String sql = "SELECT id FROM DISPOSITIVO WHERE nombre = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nombre);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            Integer id = rs.getInt("id");
            rs.close();
            ps.close();
            conn.close();
            return id;
        }

        rs.close();
        ps.close();
        conn.close();
        return null;
    }

    private int obtenerGestorAleatorio() throws Exception {
        Connection conn = ConexionDB.conectar();

        String sql = "SELECT id FROM USUARIO WHERE id_perfil = 3 ORDER BY RANDOM() LIMIT 1";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int idGestor = rs.getInt("id");
            rs.close();
            ps.close();
            conn.close();
            return idGestor;
        }

        rs.close();
        ps.close();
        conn.close();
        throw new Exception("No hay gestores disponibles");
    }

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        String tipoIncidencia = (String) jComboBoxTipo.getSelectedItem();
        String espacio = (String) jComboBoxEspacio.getSelectedItem();
        String dispositivo = (String) jComboBoxDispositivo.getSelectedItem();
        String prioridad = (String) jComboBoxPrioridad.getSelectedItem();
        String descripcion = jTextAreaDescripcion.getText();

        if (descripcion.isBlank()) {
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía");
            return;
        }

        try {
            int idTipo = obtenerIdTipoIncidencia(tipoIncidencia);
            int idEspacio = obtenerIdEspacio(espacio);
            Integer idDispositivo = obtenerIdDispositivo(dispositivo);
            int idGestor = obtenerGestorAleatorio();

            Connection conn = ConexionDB.conectar();

            String sql = """
            INSERT INTO INCIDENCIA (
                id_tipo,
                id_espacio,
                id_dispositivo,
                id_usuario_reporta,
                id_gestor_asigna,
                prioridad,
                estado,
                descripcion_incidencia
            ) VALUES (?, ?, ?, ?, ?, ?, 'Abierta', ?)
        """;

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idTipo);
            ps.setInt(2, idEspacio);
            ps.setObject(3, idDispositivo);
            ps.setInt(4, this.idUsuario);
            ps.setInt(5, idGestor);
            ps.setString(6, prioridad);
            ps.setString(7, descripcion);

            ps.executeUpdate();

            ps.close();
            conn.close();

            JOptionPane.showMessageDialog(this, "Incidencia creada correctamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear incidencia: " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IncidenciaUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jComboBoxDispositivo;
    private javax.swing.JComboBox<String> jComboBoxEspacio;
    private javax.swing.JComboBox<String> jComboBoxPrioridad;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    // End of variables declaration//GEN-END:variables
}
