
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Image;               // Para manejar imágenes y escalarlas
import javax.swing.ImageIcon;        // Para mostrar imágenes en JLabel
import javax.swing.JOptionPane;      // Para mostrar cuadros de diálogo
import javax.swing.JFrame;           // Para la ventana principal
import java.sql.Connection;          // Para la conexión con la DB
import java.sql.DriverManager;       // Para crear la conexión
import java.sql.PreparedStatement;   // Para consultas parametrizadas
import java.sql.ResultSet;           // Para obtener resultados de la consulta
import java.sql.SQLException;        // Para manejar excepciones SQL

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icono = new ImageIcon(getClass().getResource("/gestorDeIncidencias.jpeg"));

        Image img = icono.getImage().getScaledInstance(
                jLabelFotoInicio.getWidth(),
                jLabelFotoInicio.getHeight(),
                Image.SCALE_SMOOTH
        );

        jLabelFotoInicio.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFotoInicio = new javax.swing.JLabel();
        jLabelTextoUsuario = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabelTextoContraseña = new javax.swing.JLabel();
        jPasswordContraseñaUsuario = new javax.swing.JPasswordField();
        jLabelTextoTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonIniciarSesion = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabelFotoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorDeIncidencias.jpeg"))); // NOI18N
        jLabelFotoInicio.setText("jLabel1");

        jLabelTextoUsuario.setText("Usuario: ");

        jLabelTextoContraseña.setText("Contraseña: ");

        jLabelTextoTipo.setText("Tipo: ");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Técnico", "Gestor", "Admin" }));

        jButtonIniciarSesion.setText("Iniciar sesión");
        jButtonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIniciarSesionMouseClicked(evt);
            }
        });
        jButtonIniciarSesion.addActionListener(this::jButtonIniciarSesionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabelFotoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTextoUsuario)
                            .addComponent(jLabelTextoContraseña)
                            .addComponent(jLabelTextoTipo))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPasswordContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jButtonIniciarSesion))
                            .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelFotoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoUsuario)
                    .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoContraseña)
                    .addComponent(jPasswordContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIniciarSesion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionMouseClicked
        // TODO add your handling code here:
        String usuario = jTextNombreUsuario.getText();
        String contraseña = new String(jPasswordContraseñaUsuario.getPassword());
        String tipoSeleccionado = (String) jComboBoxTipo.getSelectedItem();

        try (Connection conn = ConexionDB.conectar()) {

            String sql = "SELECT u.id, u.nombre, u.apellidos, p.nombre AS perfil "
                    + "FROM USUARIO u "
                    + "JOIN PERFIL p ON u.id_perfil = p.id "
                    + "WHERE u.nombre = ? AND u.contrasena = ?";

            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, usuario);
                ps.setString(2, contraseña);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    int idUsuario = rs.getInt("id");
                    String nombreCompleto = rs.getString("nombre") + " " + rs.getString("apellidos");
                    String perfilReal = rs.getString("perfil"); // Perfil real desde la DB

                    if (!tipoSeleccionado.equals(perfilReal)) {
                        JOptionPane.showMessageDialog(this,
                                "Tipo de usuario incorrecto",
                                "Error de acceso",
                                JOptionPane.ERROR_MESSAGE
                        );
                        jPasswordContraseñaUsuario.setText("");
                        return;
                    }

                    switch (perfilReal) {
                        case "Usuario":
                            VistaUsuario vUser = new VistaUsuario(idUsuario, nombreCompleto);
                            vUser.setVisible(true);
                            break;
                        case "Técnico":
                            VistaTecnico vTec = new VistaTecnico(idUsuario, nombreCompleto);
                            vTec.setVisible(true);
                            break;
                        case "Gestor":
                            VistaGestor vg = new VistaGestor(idUsuario, nombreCompleto);
                            vg.setVisible(true);
                            break;
                        case "Admin":
                            VistaAdmin vAdminGestor = new VistaAdmin(idUsuario, nombreCompleto);
                            vAdminGestor.setVisible(true);
                            break;
                    }

                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error de acceso", JOptionPane.ERROR_MESSAGE);
                    jPasswordContraseñaUsuario.setText("");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    private boolean validarUsuario(String usuario, String contraseña, String tipo) {
        Connection conn = ConexionDB.conectar();
        if (conn == null) {
            return false;
        }

        String sql = "SELECT U.id, P.nombre "
                + "FROM USUARIO U "
                + "JOIN PERFIL P ON U.id_perfil = P.id "
                + "WHERE U.nombre = ? AND U.contrasena = ? AND P.nombre = ?";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, usuario);
            ps.setString(2, contraseña);
            ps.setString(3, tipo);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return true;
            } else {
                return false;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al consultar usuario:\n" + e.getMessage());
            return false;
        } finally {
            try {
                conn.close();
            } catch (SQLException ignored) {
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonIniciarSesion;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelFotoInicio;
    private javax.swing.JLabel jLabelTextoContraseña;
    private javax.swing.JLabel jLabelTextoTipo;
    private javax.swing.JLabel jLabelTextoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordContraseñaUsuario;
    private javax.swing.JTextField jTextNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
