/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tarde
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaTecnico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaTecnico.class.getName());

    /**
     * Creates new form VistaTecnico
     */
    public VistaTecnico() {
        initComponents();
        setLocationRelativeTo(null);

    }

    private int idUsuario;
    private String nombreUsuario;

    public VistaTecnico(int idUsuario, String nombreUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        jLabelNombreUsuario.setText(nombreUsuario);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jButtonResolver = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jTextFieldIdResolver = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();
        jButtonAgregar2 = new javax.swing.JButton();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jLabelImagen = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jTextFieldFechaInicio1 = new javax.swing.JTextField();
        jTextFieldNuevoTipo = new javax.swing.JTextField();
        jTextFieldTipoIncidencia1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabelNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonResolver.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButtonResolver.setText("Resolver Incidencia");
        jButtonResolver.addActionListener(this::jButtonResolverActionPerformed);

        jButtonVer.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonVer.setText("Ver Incidencias");
        jButtonVer.addActionListener(this::jButtonVerActionPerformed);

        jButtonAgregar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButtonAgregar.setText("Agregar tipo de incidencia");
        jButtonAgregar.addActionListener(this::jButtonAgregarActionPerformed);

        jButtonAgregar1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButtonAgregar1.setText("Listar Incidencias por Tipo");
        jButtonAgregar1.addActionListener(this::jButtonAgregar1ActionPerformed);

        jButtonAgregar2.setFont(new java.awt.Font("Liberation Sans", 0, 11)); // NOI18N
        jButtonAgregar2.setText("Consultar Incidencias por Fecha");
        jButtonAgregar2.addActionListener(this::jButtonAgregar2ActionPerformed);

        jTextFieldFechaInicio.addActionListener(this::jTextFieldFechaInicioActionPerformed);

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotoTecnico.png"))); // NOI18N
        jLabelImagen.setToolTipText("");

        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addActionListener(this::jButtonCerrarSesionActionPerformed);

        jTextFieldFechaInicio1.addActionListener(this::jTextFieldFechaInicio1ActionPerformed);

        jTextFieldNuevoTipo.addActionListener(this::jTextFieldNuevoTipoActionPerformed);

        jTextFieldTipoIncidencia1.addActionListener(this::jTextFieldTipoIncidencia1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldIdResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldFechaInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTipoIncidencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCerrarSesion)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jTextFieldIdResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTipoIncidencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonCerrarSesion)))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverActionPerformed

        String idTexto = jTextFieldIdResolver.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir el ID de la incidencia.");
            return;
        }

        int idIncidencia;
        try {
            idIncidencia = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Introduce un ID numérico válido.");
            return;
        }

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            String sql = "SELECT estado, id_tecnico_asignado FROM INCIDENCIA WHERE id = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setInt(1, idIncidencia);
                ResultSet rs = ps.executeQuery();

                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "No se encontró ninguna incidencia con ese ID.");
                    return;
                }

                String estado = rs.getString("estado");
                int idTecnicoAsignado = rs.getInt("id_tecnico_asignado");

                if (idTecnicoAsignado != this.idUsuario) {
                    JOptionPane.showMessageDialog(this, "Esta incidencia no está asignada a tu ID.");
                    return;
                }

                if ("En espera".equalsIgnoreCase(estado)) {
                    JOptionPane.showMessageDialog(this, "No puedes resolver una incidencia en estado 'En espera'.");
                    return;
                }

                if ("Resuelta".equalsIgnoreCase(estado)) {
                    JOptionPane.showMessageDialog(this, "No puedes resolver una incidencia en estado 'Resuelta'.");
                    return;
                }

                IncidenciaTecnico ventana = new IncidenciaTecnico(idIncidencia);
                ventana.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al validar la incidencia: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButtonResolverActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        String[] columnas = {"ID", "Tipo", "Prioridad", "Estado", "Descripción", "Fecha Entrada"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

        String sql = "SELECT i.id, t.descripcion, i.prioridad, i.estado, i.descripcion_incidencia, i.fecha_entrada "
                + "FROM INCIDENCIA i "
                + "JOIN TIPO_INCIDENCIA t ON i.id_tipo = t.id "
                + "WHERE i.id_tecnico_asignado = ?";

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setInt(1, this.idUsuario);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = {
                        rs.getInt("id"),
                        rs.getString("descripcion"),
                        rs.getString("prioridad"),
                        rs.getString("estado"),
                        rs.getString("descripcion_incidencia"),
                        rs.getString("fecha_entrada")
                    };
                    modelo.addRow(fila);
                }

                javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                scrollPane.setPreferredSize(new java.awt.Dimension(800, 400));

                if (modelo.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No tienes incidencias asignadas actualmente.");
                } else {
                    JOptionPane.showMessageDialog(this, scrollPane, "Mis Incidencias Asignadas", JOptionPane.PLAIN_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar tus incidencias: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:

        String descripcion = jTextFieldNuevoTipo.getText().trim();

        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce una descripción para el tipo de incidencia.");
            return;
        }

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            String checkSql = "SELECT id FROM TIPO_INCIDENCIA WHERE LOWER(descripcion) = LOWER(?)";
            try (PreparedStatement checkPs = conn.prepareStatement(checkSql)) {
                checkPs.setString(1, descripcion);
                ResultSet rs = checkPs.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Ese tipo de incidencia ya existe.");
                    return;
                }
            }

            String insertSql = "INSERT INTO TIPO_INCIDENCIA (descripcion) VALUES (?)";
            try (PreparedStatement insertPs = conn.prepareStatement(insertSql)) {
                insertPs.setString(1, descripcion);
                insertPs.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Tipo de incidencia agregado correctamente.");
            jTextFieldNuevoTipo.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar tipo de incidencia: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed

        String tipoBuscado = jTextFieldNuevoTipo.getText().trim();

        if (tipoBuscado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un tipo de incidencia (ej: Problema de red).");
            return;
        }

        String[] columnas = {"ID", "Tipo", "Prioridad", "Estado", "Descripción"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

        String sql = "SELECT i.id, t.descripcion, i.prioridad, i.estado, i.descripcion_incidencia "
                + "FROM INCIDENCIA i "
                + "JOIN TIPO_INCIDENCIA t ON i.id_tipo = t.id "
                + "WHERE i.id_tecnico_asignado = ? AND t.descripcion LIKE ?";

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setInt(1, this.idUsuario);
                ps.setString(2, "%" + tipoBuscado + "%");

                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = {
                        rs.getInt("id"),
                        rs.getString("descripcion"),
                        rs.getString("prioridad"),
                        rs.getString("estado"),
                        rs.getString("descripcion_incidencia")
                    };
                    modelo.addRow(fila);
                }

                if (modelo.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No tienes incidencias asignadas de tipo: " + tipoBuscado);
                } else {
                    javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                    scrollPane.setPreferredSize(new java.awt.Dimension(800, 400));
                    JOptionPane.showMessageDialog(this, scrollPane, "Incidencias de " + tipoBuscado, JOptionPane.PLAIN_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al filtrar por tipo: " + e.getMessage());
        }

    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    private void jButtonAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar2ActionPerformed
        String fechaIni = jTextFieldFechaInicio1.getText().trim();
        String fechaFin = jTextFieldFechaInicio.getText().trim();

        if (fechaIni.isEmpty() || fechaFin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce ambas fechas (formato YYYY-MM-DD).");
            return;
        }

        String[] columnas = {"ID", "Estado", "Prioridad", "Fecha Entrada", "Descripción"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

        String sql = "SELECT id, estado, prioridad, fecha_entrada, descripcion_incidencia "
                + "FROM INCIDENCIA "
                + "WHERE id_tecnico_asignado = ? "
                + "AND fecha_entrada BETWEEN ? AND ? ORDER BY fecha_entrada ASC";

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setInt(1, this.idUsuario);
                ps.setString(2, fechaIni + " 00:00:00");
                ps.setString(3, fechaFin + " 23:59:59");

                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = {
                        rs.getInt("id"),
                        rs.getString("estado"),
                        rs.getString("prioridad"),
                        rs.getString("fecha_entrada"),
                        rs.getString("descripcion_incidencia")
                    };
                    modelo.addRow(fila);
                }

                if (modelo.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No hay incidencias asignadas entre " + fechaIni + " y " + fechaFin);
                } else {
                    javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                    scrollPane.setPreferredSize(new java.awt.Dimension(800, 400));
                    JOptionPane.showMessageDialog(this, scrollPane, "Incidencias del periodo", JOptionPane.PLAIN_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al consultar por fechas: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonAgregar2ActionPerformed

    private void jTextFieldFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaInicioActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jTextFieldFechaInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaInicio1ActionPerformed

    private void jTextFieldNuevoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNuevoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNuevoTipoActionPerformed

    private void jTextFieldTipoIncidencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoIncidencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoIncidencia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaTecnico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonAgregar2;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonResolver;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldFechaInicio1;
    private javax.swing.JTextField jTextFieldIdResolver;
    private javax.swing.JTextField jTextFieldNuevoTipo;
    private javax.swing.JTextField jTextFieldTipoIncidencia1;
    // End of variables declaration//GEN-END:variables
}
