/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tarde
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaGestor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGestor.class.getName());
    private int idUser;
    private String nombre;

    /**
     * Creates new form VistaGestor
     */
    public VistaGestor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public VistaGestor(int id, String nombreUser) {
        initComponents();
        setLocationRelativeTo(null);
        this.idUser = id;
        this.nombre = nombreUser;
        jLabelNombreGestor.setText(nombreUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtorDarAltaIncidencia = new javax.swing.JButton();
        jButtorAsignar = new javax.swing.JButton();
        jButtonEspera = new javax.swing.JButton();
        jButtorListarTecnico = new javax.swing.JButton();
        jLabelTecnico = new javax.swing.JLabel();
        jTextFieldTecnico = new javax.swing.JTextField();
        jButtorListarTipo = new javax.swing.JButton();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jButtorListarEspera = new javax.swing.JButton();
        jLabelNombreGestor = new javax.swing.JLabel();
        jLabelIncidencia = new javax.swing.JLabel();
        jTextFieldIdIncidencia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtorDarAltaIncidencia.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtorDarAltaIncidencia.setText("Dar de Alta");
        jButtorDarAltaIncidencia.addActionListener(this::jButtorDarAltaIncidenciaActionPerformed);

        jButtorAsignar.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButtorAsignar.setText("Asignar Incidencia");
        jButtorAsignar.addActionListener(this::jButtorAsignarActionPerformed);

        jButtonEspera.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButtonEspera.setText("Poner en Espera");
        jButtonEspera.addActionListener(this::jButtonEsperaActionPerformed);

        jButtorListarTecnico.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButtorListarTecnico.setText("Listar Incidencias");
        jButtorListarTecnico.addActionListener(this::jButtorListarTecnicoActionPerformed);

        jLabelTecnico.setText("Técnico:");

        jTextFieldTecnico.addActionListener(this::jTextFieldTecnicoActionPerformed);

        jButtorListarTipo.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jButtorListarTipo.setText("Listar Incidencias");
        jButtorListarTipo.addActionListener(this::jButtorListarTipoActionPerformed);

        jLabelTipo.setText("Tipo:");

        jTextFieldTipo.addActionListener(this::jTextFieldTipoActionPerformed);

        jButtorListarEspera.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtorListarEspera.setText("Listar Incidencias en Espera");
        jButtorListarEspera.addActionListener(this::jButtorListarEsperaActionPerformed);

        jLabelNombreGestor.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabelNombreGestor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelIncidencia.setText("Id incidencia:");

        jTextFieldIdIncidencia.addActionListener(this::jTextFieldIdIncidenciaActionPerformed);

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtorDarAltaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtorAsignar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jButtorListarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(36, 36, 36))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jButtonEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(36, 36, 36)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelIncidencia)
                                                .addComponent(jLabelTecnico))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButtorListarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabelTipo)
                                            .addGap(54, 54, 54)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldIdIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(428, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtorListarEspera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(104, 104, 104))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButtorDarAltaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtorAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIncidencia)
                            .addComponent(jTextFieldIdIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtorListarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTecnico)
                            .addComponent(jTextFieldTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtorListarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipo)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtorListarEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtorDarAltaIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtorDarAltaIncidenciaActionPerformed
        String idIncidenciaStr = jTextFieldIdIncidencia.getText().trim();
        String nombreTecnico = jTextFieldTecnico.getText().trim();

        if (idIncidenciaStr.isEmpty() || nombreTecnico.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena ambos campos.");
            return;
        }

        try (Connection conn = ConexionDB.conectar()) {
            String sqlCheck = "SELECT estado FROM INCIDENCIA WHERE id = ?";
            PreparedStatement psCheck = conn.prepareStatement(sqlCheck);
            psCheck.setInt(1, Integer.parseInt(idIncidenciaStr));
            ResultSet rs = psCheck.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "La incidencia con ID " + idIncidenciaStr + " no existe.");
                return;
            }

            if (!"En espera".equals(rs.getString("estado"))) {
                JOptionPane.showMessageDialog(this, "Solo se pueden asignar incidencias que estén 'En espera'.");
                return;
            }

            String sqlTecnico = "SELECT id FROM USUARIO WHERE nombre = ? AND id_perfil = 2";
            PreparedStatement psTec = conn.prepareStatement(sqlTecnico);
            psTec.setString(1, nombreTecnico);
            ResultSet rsTec = psTec.executeQuery();

            if (!rsTec.next()) {
                JOptionPane.showMessageDialog(this, "No se encontró ningún técnico con el nombre: " + nombreTecnico);
                return;
            }
            int idTecnico = rsTec.getInt("id");

            String sqlUpdate = "UPDATE INCIDENCIA SET id_tecnico_asignado = ?, estado = 'Asignada' WHERE id = ?";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setInt(1, idTecnico);
            psUpdate.setInt(2, Integer.parseInt(idIncidenciaStr));

            int filas = psUpdate.executeUpdate();
            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Incidencia asignada correctamente a " + nombreTecnico);
                this.dispose(); // Cierra esta ventana tras el éxito
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la incidencia debe ser un número.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtorDarAltaIncidenciaActionPerformed

    private void jButtorAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtorAsignarActionPerformed
        IncidenciaGestor ventanaAsignar = new IncidenciaGestor();
        ventanaAsignar.setVisible(true);
        ventanaAsignar.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButtorAsignarActionPerformed

    private void jButtonEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsperaActionPerformed
        // TODO add your handling code here:
        String idIncidenciaStr = jTextFieldIdIncidencia.getText().trim();

    if (idIncidenciaStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, introduce el ID de la incidencia en el campo 'Id incidencia'.");
        return;
    }

    String sql = "UPDATE INCIDENCIA SET estado = 'En espera' WHERE id = ?";

    try (Connection conn = ConexionDB.conectar()) {
        if (conn == null) return;

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            int idIncidencia = Integer.parseInt(idIncidenciaStr);
            ps.setInt(1, idIncidencia);

            int filasAfectadas = ps.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "La incidencia con ID " + idIncidencia + " ha sido puesta 'En espera' correctamente.");
                jTextFieldIdIncidencia.setText(""); // Limpiamos el campo tras el éxito
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna incidencia con el ID: " + idIncidencia);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: El ID de la incidencia debe ser un número válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_jButtonEsperaActionPerformed

    private void jButtorListarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtorListarTecnicoActionPerformed
        // TODO add your handling code here:
        String nombreTecnico = jTextFieldTecnico.getText().trim();

    if (nombreTecnico.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, introduce el nombre del técnico.");
        return;
    }

    String[] columnas = {"ID", "Técnico", "Tipo", "Prioridad", "Estado", "Descripción"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

    String sql = "SELECT i.id, u.nombre, t.descripcion, i.prioridad, i.estado, i.descripcion_incidencia "
               + "FROM INCIDENCIA i "
               + "JOIN TIPO_INCIDENCIA t ON i.id_tipo = t.id "
               + "JOIN USUARIO u ON i.id_tecnico_asignado = u.id "
               + "WHERE u.nombre = ?";

    try (Connection conn = ConexionDB.conectar()) {
        if (conn == null) {
            return;
        }

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, nombreTecnico);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id"),
                    rs.getString("nombre"), 
                    rs.getString("descripcion"),
                    rs.getString("prioridad"),
                    rs.getString("estado"),
                    rs.getString("descripcion_incidencia")
                };
                modelo.addRow(fila);
            }

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron incidencias asignadas exactamente al técnico: " + nombreTecnico);
            } else {
                javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                scrollPane.setPreferredSize(new java.awt.Dimension(850, 400));

                JOptionPane.showMessageDialog(this, scrollPane, "Incidencias asignadas a: " + nombreTecnico, JOptionPane.PLAIN_MESSAGE);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al filtrar por técnico: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButtorListarTecnicoActionPerformed

    private void jTextFieldTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTecnicoActionPerformed

    private void jButtorListarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtorListarTipoActionPerformed
        // TODO add your handling code here:

        String tipoBuscado = jTextFieldTipo.getText().trim();

        if (tipoBuscado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un tipo de incidencia (ej: Problema de red).");
            return;
        }

        String[] columnas = {"ID", "Tipo", "Prioridad", "Estado", "Descripción"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

        String sql = "SELECT i.id, t.descripcion, i.prioridad, i.estado, i.descripcion_incidencia "
                + "FROM INCIDENCIA i "
                + "JOIN TIPO_INCIDENCIA t ON i.id_tipo = t.id "
                + "WHERE t.descripcion LIKE ?";

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, "%" + tipoBuscado + "%");

                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    Object[] fila = {
                        rs.getInt("id"),
                        rs.getString("descripcion"),
                        rs.getString("prioridad"),
                        rs.getString("estado"),
                        rs.getString("descripcion_incidencia")
                    };
                    modelo.addRow(fila);
                }

                if (modelo.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No tienes incidencias asignadas de tipo: " + tipoBuscado);
                } else {
                    javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                    scrollPane.setPreferredSize(new java.awt.Dimension(800, 400));
                    JOptionPane.showMessageDialog(this, scrollPane, "Incidencias de " + tipoBuscado, JOptionPane.PLAIN_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al filtrar por tipo: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtorListarTipoActionPerformed

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jButtorListarEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtorListarEsperaActionPerformed

        String[] columnas = {"ID", "Fecha Entrada", "Descripción"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

    String sql = "SELECT id, fecha_entrada, descripcion_incidencia FROM INCIDENCIA WHERE estado = 'En espera'";

    try (Connection conn = ConexionDB.conectar()) {
        if (conn == null) return;

        try (PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            boolean hayDatos = false;
            while (rs.next()) {
                hayDatos = true;
                Object[] fila = {
                    rs.getInt("id"),
                    rs.getString("fecha_entrada"),
                    rs.getString("descripcion_incidencia")
                };
                modelo.addRow(fila);
            }

            if (!hayDatos) {
                JOptionPane.showMessageDialog(this, "No hay ninguna incidencia en estado 'En espera' actualmente.");
            } else {
                javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                scrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

                JOptionPane.showMessageDialog(this, scrollPane, "Incidencias En Espera", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al listar incidencias en espera: " + e.getMessage());
        e.printStackTrace();
    }


    }//GEN-LAST:event_jButtorListarEsperaActionPerformed

    private void jTextFieldIdIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdIncidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdIncidenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaGestor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEspera;
    private javax.swing.JButton jButtorAsignar;
    private javax.swing.JButton jButtorDarAltaIncidencia;
    private javax.swing.JButton jButtorListarEspera;
    private javax.swing.JButton jButtorListarTecnico;
    private javax.swing.JButton jButtorListarTipo;
    private javax.swing.JLabel jLabelIncidencia;
    private javax.swing.JLabel jLabelNombreGestor;
    private javax.swing.JLabel jLabelTecnico;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIdIncidencia;
    private javax.swing.JTextField jTextFieldTecnico;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
