
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class VistaUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaUsuario.class.getName());

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario() {
        initComponents();
        setLocationRelativeTo(null);

    }

    private int idUsuario;       // ID para filtrar incidencias
    private String nombreUsuario; // Nombre completo para mostrar

    public VistaUsuario(int idUsuario, String nombreUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        jLabel2.setText(nombreUsuario); // muestra nombre en JLabel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonConsultarIncidencias = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddIncidencia = new javax.swing.JButton();
        jButtonListarIncidencias = new javax.swing.JButton();
        jTextFieldIdConsulta = new javax.swing.JTextField();
        jButtonSolicitarReapertura = new javax.swing.JButton();
        jTextFieldIdReapertura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButonCerrarSesion = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConsultarIncidencias.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonConsultarIncidencias.setText("Consultar incidencia por id");
        jButtonConsultarIncidencias.addActionListener(this::jButtonConsultarIncidenciasActionPerformed);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonAddIncidencia.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonAddIncidencia.setText("Añadir incidencia");
        jButtonAddIncidencia.addActionListener(this::jButtonAddIncidenciaActionPerformed);

        jButtonListarIncidencias.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonListarIncidencias.setText("Listar incidencias");
        jButtonListarIncidencias.addActionListener(this::jButtonListarIncidenciasActionPerformed);

        jTextFieldIdConsulta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonSolicitarReapertura.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonSolicitarReapertura.setText("Solicitar reapertura por id");
        jButtonSolicitarReapertura.addActionListener(this::jButtonSolicitarReaperturaActionPerformed);

        jTextFieldIdReapertura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotoUsuario.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel4.setText("Incidencias");

        jButonCerrarSesion.setText("Cerrar sesión");
        jButonCerrarSesion.addActionListener(this::jButonCerrarSesionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddIncidencia)
                    .addComponent(jButtonListarIncidencias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonConsultarIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSolicitarReapertura, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIdConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jTextFieldIdReapertura)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButonCerrarSesion)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonAddIncidencia)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonListarIncidencias)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConsultarIncidencias)
                            .addComponent(jTextFieldIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSolicitarReapertura)
                            .addComponent(jTextFieldIdReapertura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jButonCerrarSesion)
                .addGap(185, 185, 185))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarIncidenciasActionPerformed
        // TODO add your handling code here:
        String idTexto = jTextFieldIdConsulta.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce un ID de incidencia", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idIncidencia;
        try {
            idIncidencia = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = ConexionDB.conectar()) {
            if (conn == null) {
                return;
            }

            String sql = """
        SELECT id,
               descripcion_incidencia,
               estado,
               fecha_entrada,
               descripcion_solucion,
               fecha_cierre
        FROM INCIDENCIA
        WHERE id_usuario_reporta = ? AND id = ?
        """;

            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setInt(1, idUsuario);
                ps.setInt(2, idIncidencia);

                ResultSet rs = ps.executeQuery();
                StringBuilder sb = new StringBuilder();

                if (rs.next()) {
                    sb.append("ID: ").append(rs.getInt("id"))
                            .append("\nEstado: ").append(rs.getString("estado"))
                            .append("\nFecha entrada: ").append(rs.getString("fecha_entrada"))
                            .append("\nDescripción: ").append(rs.getString("descripcion_incidencia"));

                    String solucion = rs.getString("descripcion_solucion");
                    String fechaCierre = rs.getString("fecha_cierre");

                    if (solucion != null && !solucion.isEmpty()) {
                        sb.append("\nSolución: ").append(solucion);
                        if (fechaCierre != null) {
                            sb.append("\nFecha cierre: ").append(fechaCierre);
                        }
                    }
                }

                if (sb.length() == 0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "No se encontró ninguna incidencia con ese ID para tu usuario.",
                            "Incidencias",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            sb.toString(),
                            "Incidencia #" + idIncidencia,
                            JOptionPane.INFORMATION_MESSAGE
                    );
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al consultar la incidencia: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButtonConsultarIncidenciasActionPerformed

    private void jButtonAddIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIncidenciaActionPerformed
        // TODO add your handling code here:
        IncidenciaUsuario iu = new IncidenciaUsuario(this.idUsuario);
        iu.setVisible(true);


    }//GEN-LAST:event_jButtonAddIncidenciaActionPerformed

    private void jButtonListarIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarIncidenciasActionPerformed
        // TODO add your handling code here:
        String[] columnas = {"ID", "Estado", "Fecha Entrada", "Descripción", "Solución", "Fecha Cierre"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

    try (Connection conn = ConexionDB.conectar()) {
        if (conn == null) return;

        String sql = "SELECT id, estado, fecha_entrada, descripcion_incidencia, descripcion_solucion, fecha_cierre "
                   + "FROM INCIDENCIA WHERE id_usuario_reporta = ?"; 

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, idUsuario); 

            ResultSet rs = ps.executeQuery();
            boolean hayDatos = false;

            while (rs.next()) {
                hayDatos = true;
                Object[] fila = {
                    rs.getInt("id"),
                    rs.getString("estado"),
                    rs.getString("fecha_entrada"),
                    rs.getString("descripcion_incidencia"),
                    rs.getString("descripcion_solucion") == null ? "" : rs.getString("descripcion_solucion"),
                    rs.getString("fecha_cierre") == null ? "" : rs.getString("fecha_cierre")
                };
                modelo.addRow(fila);
            }

            if (!hayDatos) {
                JOptionPane.showMessageDialog(this, "No tienes incidencias registradas.", "Incidencias", JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JTable tabla = new javax.swing.JTable(modelo);
                tabla.setEnabled(false); // Para que sea solo de lectura
                
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabla);
                scrollPane.setPreferredSize(new java.awt.Dimension(800, 400));

                JOptionPane.showMessageDialog(this, scrollPane, "Mis Incidencias", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al consultar incidencias: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButtonListarIncidenciasActionPerformed

    private void jButtonSolicitarReaperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarReaperturaActionPerformed
        // TODO add your handling code here:
        String idTexto = jTextFieldIdReapertura.getText().trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce un ID de incidencia", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idIncidencia;
        try {
            idIncidencia = Integer.parseInt(idTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = ConexionDB.conectar();
        if (conn == null) {
            return;
        }

        try {
            String sqlSelect = "SELECT estado FROM INCIDENCIA WHERE id = ? AND id_usuario_reporta = ?";
            PreparedStatement psSelect = conn.prepareStatement(sqlSelect);
            psSelect.setInt(1, idIncidencia);
            psSelect.setInt(2, idUsuario);

            ResultSet rs = psSelect.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna incidencia con ese ID para tu usuario.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                rs.close();
                psSelect.close();
                conn.close();
                return;
            }

            String estadoActual = rs.getString("estado");
            rs.close();
            psSelect.close();

            if (!(estadoActual.equals("Resuelta"))) {
                JOptionPane.showMessageDialog(this, "No se puede reabrir una incidencia que no esté resuelta.", "Aviso", JOptionPane.WARNING_MESSAGE);
                conn.close();
                return;
            }
            // Cambiar estado a "En espera" y registrar fecha de reapertura
            String sqlUpdate = "UPDATE INCIDENCIA SET estado = 'En espera', fecha_reapertura = CURRENT_TIMESTAMP WHERE id = ?";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setInt(1, idIncidencia);

            int filas = psUpdate.executeUpdate();
            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Incidencia #" + idIncidencia + " solicitada para reapertura correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo solicitar la reapertura.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            psUpdate.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al solicitar la reapertura: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonSolicitarReaperturaActionPerformed

    private void jButonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonCerrarSesionActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButonCerrarSesion;
    private javax.swing.JButton jButtonAddIncidencia;
    private javax.swing.JButton jButtonConsultarIncidencias;
    private javax.swing.JButton jButtonListarIncidencias;
    private javax.swing.JButton jButtonSolicitarReapertura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIdConsulta;
    private javax.swing.JTextField jTextFieldIdReapertura;
    // End of variables declaration//GEN-END:variables

}
